components:
  schemas:
    BaseServiceDTO:
      type: object
      properties:
        prefix:
          type: string
        name:
          type: string
        driverType:
          $ref: './enums.yaml#/components/schemas/DriverType'
        version:
          type: string
        description:
          type: string
        icon:
          type: string
          format: url
        source:
          description: URL to git repository
          type: string
          format: url

    CreateServiceDTO:
      allOf:
        - $ref: '#/components/schemas/BaseServiceDTO'
        - type: object
          required:
            - prefix
            - name
            - driverType
            - version

    UpdateServiceDTO:
      allOf:
        - $ref: '#/components/schemas/BaseServiceDTO'
        - type: object

    PublicServiceDTO:
      type: object
      required:
        - prefix
        - name
        - version
      properties:
        prefix:
          type: string
        name:
          type: string
        version:
          type: string
        description:
          type: string
        icon:
          type: string
          format: url

    ServiceDTO:
      allOf:
        - $ref: '#/components/schemas/BaseServiceDTO'
        - type: object
          required:
            - id
            - prefix
            - name
            - driverType
            - version
            - source
          properties:
            id:
              type: string
              format: uuid
            port:
              type: integer